### ISSUE TITLE
单抽的几个问题

### ISSUE THREAD

**Issue by weixingp5** [dyingsunlight/mock-kakin#4]
单抽有一定几率卡在加载资源（0/4）
单抽抽10次后，补给记录只有最后一项会更新

**Comment by dyingsunlight** [comment]
确实会有概率会卡在加载资源中，检查后发现卡住的同时并没有发出请求。。。晚点再找找原因试着修复。

然后关于补给记录只有最后一项会更新，这个应该没问题。。。游戏内就是这样吧，有些不太理解

**Comment by weixingp5** [comment]
关于补给记录，10抽后再单抽，补给记录只刷新最后一条，前9条记录还是保持为第一次10抽的记录，没有那种“上拉”的效果

**Comment by dyingsunlight** [comment]
![image](https://user-images.githubusercontent.com/10810452/37392932-9deeb0c0-27aa-11e8-8b0a-20853a5d72c0.png)
卡在加载资源（0/4）的问题已经解决了，等稍后再提交上去。
另一个，补给记录只刷新最后一条的问题，暂时没有发现你说的BUG，你看一下图片吧

**Comment by dyingsunlight** [comment]
呃、、我找到只刷新最后一条的BUG了。。。正在处理

**Comment by dyingsunlight** [comment]
非常感谢你的反馈，目前这两个BUG已经修复完成了～还发现有其他问题的话可以顺便告诉我

**Comment by weixingp5** [comment]
还发现了一个bug： 测试的时候，S角色的数量不符，7个S 一般只能出 2 3个 （突然发现A级角色也是这样）
![image](https://user-images.githubusercontent.com/7765581/37396059-cbc1b4fe-27b2-11e8-87cc-f6abb92f4c1c.png)

**Comment by dyingsunlight** [comment]
前几天我发现过这个问题， 可惜一直没找到原因，刚刚才发现角色卡的概率被算到角色碎片里去了，因为名字没有区分我去。。。不过现在已经可以了哦

**Comment by weixingp5** [comment]
黑核碎片的图片你没放进去 ：3
妖刀·赤染樱 和 妖精剑希尔文 匹配ID都是Katana_M23_171_4

**Comment by dyingsunlight** [comment]
呃、、漏了挺多东西啊哈哈哈
